[package]
name = "shared"
version = "0.1.0"
edition = "2021"
rust-version = "1.82"

[dependencies]
eyre.workspace = true
tracing.workspace = true
windows.workspace = true
unicase.workspace = true
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
directories = "6.0.0"
backtrace = "0.3.74"
toml = "0.8.19"
tokio = { version = "1.43.0", features = ["net", "rt"] }

[lints]
workspace = true
